apiVersion: v2
name: sample-microservice
description: A Helm chart for the sample microservice
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: Your Name
    email: your.email@example.com
